# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up git release environment
      run: |
        if [[ "$GITHUB_REF" = refs/heads/* ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
        elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
          export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
        fi
        echo VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH}
        echo VERSIONING_GIT_TAG=${VERSIONING_GIT_TAG}
    - name: Effective pom
      run: mvn -B help:effective-pom
    - name: Effective settings
      run: mvn -B help:effective-settings
    - name: Build with Maven
      run: mvn -B package
      env:
        NOBAD: true
    - name: Deploy with Maven
      run: mvn -B -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/nelbrecht/buildme -Dmaven.test.skip=true -Dmaven.main.skip deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: diagnositcs
      run: |
        echo VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH}
        echo VERSIONING_GIT_TAG=${VERSIONING_GIT_TAG}
